// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: kvServerRPC.proto
// Protobuf C++ Version: 6.33.5

#include "kvServerRPC.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace raftKVRpcProctoc {

inline constexpr PutAppendReply::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        err_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR PutAppendReply::PutAppendReply(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(PutAppendReply_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PutAppendReplyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PutAppendReplyDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PutAppendReplyDefaultTypeInternal() {}
  union {
    PutAppendReply _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PutAppendReplyDefaultTypeInternal _PutAppendReply_default_instance_;

inline constexpr PutAppendArgs::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        key_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        value_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        op_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        clientid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        requestid_{0} {}

template <typename>
PROTOBUF_CONSTEXPR PutAppendArgs::PutAppendArgs(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(PutAppendArgs_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PutAppendArgsDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PutAppendArgsDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PutAppendArgsDefaultTypeInternal() {}
  union {
    PutAppendArgs _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PutAppendArgsDefaultTypeInternal _PutAppendArgs_default_instance_;

inline constexpr GetReply::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        err_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        value_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR GetReply::GetReply(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(GetReply_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct GetReplyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetReplyDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetReplyDefaultTypeInternal() {}
  union {
    GetReply _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetReplyDefaultTypeInternal _GetReply_default_instance_;

inline constexpr GetArgs::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        key_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        clientid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        requestid_{0} {}

template <typename>
PROTOBUF_CONSTEXPR GetArgs::GetArgs(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(GetArgs_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct GetArgsDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetArgsDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetArgsDefaultTypeInternal() {}
  union {
    GetArgs _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetArgsDefaultTypeInternal _GetArgs_default_instance_;
}  // namespace raftKVRpcProctoc
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_kvServerRPC_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_kvServerRPC_2eproto = nullptr;
const ::uint32_t
    TableStruct_kvServerRPC_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::raftKVRpcProctoc::GetArgs, _impl_._has_bits_),
        6, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::raftKVRpcProctoc::GetArgs, _impl_.key_),
        PROTOBUF_FIELD_OFFSET(::raftKVRpcProctoc::GetArgs, _impl_.clientid_),
        PROTOBUF_FIELD_OFFSET(::raftKVRpcProctoc::GetArgs, _impl_.requestid_),
        0,
        1,
        2,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::raftKVRpcProctoc::GetReply, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::raftKVRpcProctoc::GetReply, _impl_.err_),
        PROTOBUF_FIELD_OFFSET(::raftKVRpcProctoc::GetReply, _impl_.value_),
        0,
        1,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::raftKVRpcProctoc::PutAppendArgs, _impl_._has_bits_),
        8, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::raftKVRpcProctoc::PutAppendArgs, _impl_.key_),
        PROTOBUF_FIELD_OFFSET(::raftKVRpcProctoc::PutAppendArgs, _impl_.value_),
        PROTOBUF_FIELD_OFFSET(::raftKVRpcProctoc::PutAppendArgs, _impl_.op_),
        PROTOBUF_FIELD_OFFSET(::raftKVRpcProctoc::PutAppendArgs, _impl_.clientid_),
        PROTOBUF_FIELD_OFFSET(::raftKVRpcProctoc::PutAppendArgs, _impl_.requestid_),
        0,
        1,
        2,
        3,
        4,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::raftKVRpcProctoc::PutAppendReply, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::raftKVRpcProctoc::PutAppendReply, _impl_.err_),
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::raftKVRpcProctoc::GetArgs)},
        {9, sizeof(::raftKVRpcProctoc::GetReply)},
        {16, sizeof(::raftKVRpcProctoc::PutAppendArgs)},
        {29, sizeof(::raftKVRpcProctoc::PutAppendReply)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::raftKVRpcProctoc::_GetArgs_default_instance_._instance,
    &::raftKVRpcProctoc::_GetReply_default_instance_._instance,
    &::raftKVRpcProctoc::_PutAppendArgs_default_instance_._instance,
    &::raftKVRpcProctoc::_PutAppendReply_default_instance_._instance,
};
const char descriptor_table_protodef_kvServerRPC_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\021kvServerRPC.proto\022\020raftKVRpcProctoc\";\n"
    "\007GetArgs\022\013\n\003Key\030\001 \001(\014\022\020\n\010ClientId\030\002 \001(\014\022"
    "\021\n\tRequestId\030\003 \001(\005\"&\n\010GetReply\022\013\n\003Err\030\001 "
    "\001(\014\022\r\n\005Value\030\002 \001(\014\"\\\n\rPutAppendArgs\022\013\n\003K"
    "ey\030\001 \001(\014\022\r\n\005Value\030\002 \001(\014\022\n\n\002Op\030\003 \001(\014\022\020\n\010C"
    "lientId\030\004 \001(\014\022\021\n\tRequestId\030\005 \001(\005\"\035\n\016PutA"
    "ppendReply\022\013\n\003Err\030\001 \001(\0142\233\001\n\013kvServerRpc\022"
    "N\n\tPutAppend\022\037.raftKVRpcProctoc.PutAppen"
    "dArgs\032 .raftKVRpcProctoc.PutAppendReply\022"
    "<\n\003Get\022\031.raftKVRpcProctoc.GetArgs\032\032.raft"
    "KVRpcProctoc.GetReplyb\006proto3"
};
static ::absl::once_flag descriptor_table_kvServerRPC_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_kvServerRPC_2eproto = {
    false,
    false,
    429,
    descriptor_table_protodef_kvServerRPC_2eproto,
    "kvServerRPC.proto",
    &descriptor_table_kvServerRPC_2eproto_once,
    nullptr,
    0,
    4,
    schemas,
    file_default_instances,
    TableStruct_kvServerRPC_2eproto::offsets,
    file_level_enum_descriptors_kvServerRPC_2eproto,
    file_level_service_descriptors_kvServerRPC_2eproto,
};
namespace raftKVRpcProctoc {
// ===================================================================

class GetArgs::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<GetArgs>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(GetArgs, _impl_._has_bits_);
};

GetArgs::GetArgs(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, GetArgs_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:raftKVRpcProctoc.GetArgs)
}
PROTOBUF_NDEBUG_INLINE GetArgs::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::raftKVRpcProctoc::GetArgs& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        key_(arena, from.key_),
        clientid_(arena, from.clientid_) {}

GetArgs::GetArgs(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const GetArgs& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, GetArgs_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  GetArgs* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.requestid_ = from._impl_.requestid_;

  // @@protoc_insertion_point(copy_constructor:raftKVRpcProctoc.GetArgs)
}
PROTOBUF_NDEBUG_INLINE GetArgs::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        key_(arena),
        clientid_(arena) {}

inline void GetArgs::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.requestid_ = {};
}
GetArgs::~GetArgs() {
  // @@protoc_insertion_point(destructor:raftKVRpcProctoc.GetArgs)
  SharedDtor(*this);
}
inline void GetArgs::SharedDtor(MessageLite& self) {
  GetArgs& this_ = static_cast<GetArgs&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.key_.Destroy();
  this_._impl_.clientid_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL GetArgs::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) GetArgs(arena);
}
constexpr auto GetArgs::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(GetArgs),
                                            alignof(GetArgs));
}
constexpr auto GetArgs::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_GetArgs_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &GetArgs::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<GetArgs>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &GetArgs::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<GetArgs>(), &GetArgs::ByteSizeLong,
              &GetArgs::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(GetArgs, _impl_._cached_size_),
          false,
      },
      &GetArgs::kDescriptorMethods,
      &descriptor_table_kvServerRPC_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull GetArgs_class_data_ =
        GetArgs::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
GetArgs::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&GetArgs_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(GetArgs_class_data_.tc_table);
  return GetArgs_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 0, 2>
GetArgs::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(GetArgs, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    GetArgs_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::raftKVRpcProctoc::GetArgs>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // bytes Key = 1;
    {::_pbi::TcParser::FastBS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(GetArgs, _impl_.key_)}},
    // bytes ClientId = 2;
    {::_pbi::TcParser::FastBS1,
     {18, 1, 0,
      PROTOBUF_FIELD_OFFSET(GetArgs, _impl_.clientid_)}},
    // int32 RequestId = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(GetArgs, _impl_.requestid_), 2>(),
     {24, 2, 0,
      PROTOBUF_FIELD_OFFSET(GetArgs, _impl_.requestid_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bytes Key = 1;
    {PROTOBUF_FIELD_OFFSET(GetArgs, _impl_.key_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // bytes ClientId = 2;
    {PROTOBUF_FIELD_OFFSET(GetArgs, _impl_.clientid_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // int32 RequestId = 3;
    {PROTOBUF_FIELD_OFFSET(GetArgs, _impl_.requestid_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void GetArgs::Clear() {
// @@protoc_insertion_point(message_clear_start:raftKVRpcProctoc.GetArgs)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.key_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.clientid_.ClearNonDefaultToEmpty();
    }
  }
  _impl_.requestid_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL GetArgs::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const GetArgs& this_ = static_cast<const GetArgs&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL GetArgs::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const GetArgs& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:raftKVRpcProctoc.GetArgs)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // bytes Key = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_key().empty()) {
      const ::std::string& _s = this_._internal_key();
      target = stream->WriteBytesMaybeAliased(1, _s, target);
    }
  }

  // bytes ClientId = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_clientid().empty()) {
      const ::std::string& _s = this_._internal_clientid();
      target = stream->WriteBytesMaybeAliased(2, _s, target);
    }
  }

  // int32 RequestId = 3;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (this_._internal_requestid() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<3>(
              stream, this_._internal_requestid(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:raftKVRpcProctoc.GetArgs)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t GetArgs::ByteSizeLong(const MessageLite& base) {
  const GetArgs& this_ = static_cast<const GetArgs&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t GetArgs::ByteSizeLong() const {
  const GetArgs& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:raftKVRpcProctoc.GetArgs)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    // bytes Key = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_key().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_key());
      }
    }
    // bytes ClientId = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!this_._internal_clientid().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_clientid());
      }
    }
    // int32 RequestId = 3;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (this_._internal_requestid() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_requestid());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void GetArgs::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<GetArgs*>(&to_msg);
  auto& from = static_cast<const GetArgs&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:raftKVRpcProctoc.GetArgs)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_key().empty()) {
        _this->_internal_set_key(from._internal_key());
      } else {
        if (_this->_impl_.key_.IsDefault()) {
          _this->_internal_set_key("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!from._internal_clientid().empty()) {
        _this->_internal_set_clientid(from._internal_clientid());
      } else {
        if (_this->_impl_.clientid_.IsDefault()) {
          _this->_internal_set_clientid("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (from._internal_requestid() != 0) {
        _this->_impl_.requestid_ = from._impl_.requestid_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void GetArgs::CopyFrom(const GetArgs& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:raftKVRpcProctoc.GetArgs)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void GetArgs::InternalSwap(GetArgs* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.key_, &other->_impl_.key_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.clientid_, &other->_impl_.clientid_, arena);
  swap(_impl_.requestid_, other->_impl_.requestid_);
}

::google::protobuf::Metadata GetArgs::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class GetReply::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<GetReply>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(GetReply, _impl_._has_bits_);
};

GetReply::GetReply(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, GetReply_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:raftKVRpcProctoc.GetReply)
}
PROTOBUF_NDEBUG_INLINE GetReply::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::raftKVRpcProctoc::GetReply& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        err_(arena, from.err_),
        value_(arena, from.value_) {}

GetReply::GetReply(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const GetReply& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, GetReply_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  GetReply* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:raftKVRpcProctoc.GetReply)
}
PROTOBUF_NDEBUG_INLINE GetReply::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        err_(arena),
        value_(arena) {}

inline void GetReply::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
GetReply::~GetReply() {
  // @@protoc_insertion_point(destructor:raftKVRpcProctoc.GetReply)
  SharedDtor(*this);
}
inline void GetReply::SharedDtor(MessageLite& self) {
  GetReply& this_ = static_cast<GetReply&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.err_.Destroy();
  this_._impl_.value_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL GetReply::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) GetReply(arena);
}
constexpr auto GetReply::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(GetReply),
                                            alignof(GetReply));
}
constexpr auto GetReply::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_GetReply_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &GetReply::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<GetReply>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &GetReply::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<GetReply>(), &GetReply::ByteSizeLong,
              &GetReply::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(GetReply, _impl_._cached_size_),
          false,
      },
      &GetReply::kDescriptorMethods,
      &descriptor_table_kvServerRPC_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull GetReply_class_data_ =
        GetReply::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
GetReply::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&GetReply_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(GetReply_class_data_.tc_table);
  return GetReply_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2>
GetReply::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(GetReply, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    GetReply_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::raftKVRpcProctoc::GetReply>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bytes Value = 2;
    {::_pbi::TcParser::FastBS1,
     {18, 1, 0,
      PROTOBUF_FIELD_OFFSET(GetReply, _impl_.value_)}},
    // bytes Err = 1;
    {::_pbi::TcParser::FastBS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(GetReply, _impl_.err_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bytes Err = 1;
    {PROTOBUF_FIELD_OFFSET(GetReply, _impl_.err_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // bytes Value = 2;
    {PROTOBUF_FIELD_OFFSET(GetReply, _impl_.value_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void GetReply::Clear() {
// @@protoc_insertion_point(message_clear_start:raftKVRpcProctoc.GetReply)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.err_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.value_.ClearNonDefaultToEmpty();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL GetReply::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const GetReply& this_ = static_cast<const GetReply&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL GetReply::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const GetReply& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:raftKVRpcProctoc.GetReply)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // bytes Err = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_err().empty()) {
      const ::std::string& _s = this_._internal_err();
      target = stream->WriteBytesMaybeAliased(1, _s, target);
    }
  }

  // bytes Value = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_value().empty()) {
      const ::std::string& _s = this_._internal_value();
      target = stream->WriteBytesMaybeAliased(2, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:raftKVRpcProctoc.GetReply)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t GetReply::ByteSizeLong(const MessageLite& base) {
  const GetReply& this_ = static_cast<const GetReply&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t GetReply::ByteSizeLong() const {
  const GetReply& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:raftKVRpcProctoc.GetReply)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // bytes Err = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_err().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_err());
      }
    }
    // bytes Value = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!this_._internal_value().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_value());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void GetReply::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<GetReply*>(&to_msg);
  auto& from = static_cast<const GetReply&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:raftKVRpcProctoc.GetReply)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_err().empty()) {
        _this->_internal_set_err(from._internal_err());
      } else {
        if (_this->_impl_.err_.IsDefault()) {
          _this->_internal_set_err("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!from._internal_value().empty()) {
        _this->_internal_set_value(from._internal_value());
      } else {
        if (_this->_impl_.value_.IsDefault()) {
          _this->_internal_set_value("");
        }
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void GetReply::CopyFrom(const GetReply& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:raftKVRpcProctoc.GetReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void GetReply::InternalSwap(GetReply* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.err_, &other->_impl_.err_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.value_, &other->_impl_.value_, arena);
}

::google::protobuf::Metadata GetReply::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class PutAppendArgs::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<PutAppendArgs>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(PutAppendArgs, _impl_._has_bits_);
};

PutAppendArgs::PutAppendArgs(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PutAppendArgs_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:raftKVRpcProctoc.PutAppendArgs)
}
PROTOBUF_NDEBUG_INLINE PutAppendArgs::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::raftKVRpcProctoc::PutAppendArgs& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        key_(arena, from.key_),
        value_(arena, from.value_),
        op_(arena, from.op_),
        clientid_(arena, from.clientid_) {}

PutAppendArgs::PutAppendArgs(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const PutAppendArgs& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PutAppendArgs_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  PutAppendArgs* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.requestid_ = from._impl_.requestid_;

  // @@protoc_insertion_point(copy_constructor:raftKVRpcProctoc.PutAppendArgs)
}
PROTOBUF_NDEBUG_INLINE PutAppendArgs::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        key_(arena),
        value_(arena),
        op_(arena),
        clientid_(arena) {}

inline void PutAppendArgs::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.requestid_ = {};
}
PutAppendArgs::~PutAppendArgs() {
  // @@protoc_insertion_point(destructor:raftKVRpcProctoc.PutAppendArgs)
  SharedDtor(*this);
}
inline void PutAppendArgs::SharedDtor(MessageLite& self) {
  PutAppendArgs& this_ = static_cast<PutAppendArgs&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.key_.Destroy();
  this_._impl_.value_.Destroy();
  this_._impl_.op_.Destroy();
  this_._impl_.clientid_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL PutAppendArgs::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) PutAppendArgs(arena);
}
constexpr auto PutAppendArgs::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(PutAppendArgs),
                                            alignof(PutAppendArgs));
}
constexpr auto PutAppendArgs::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_PutAppendArgs_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &PutAppendArgs::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<PutAppendArgs>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &PutAppendArgs::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<PutAppendArgs>(), &PutAppendArgs::ByteSizeLong,
              &PutAppendArgs::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(PutAppendArgs, _impl_._cached_size_),
          false,
      },
      &PutAppendArgs::kDescriptorMethods,
      &descriptor_table_kvServerRPC_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull PutAppendArgs_class_data_ =
        PutAppendArgs::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
PutAppendArgs::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&PutAppendArgs_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(PutAppendArgs_class_data_.tc_table);
  return PutAppendArgs_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 0, 0, 2>
PutAppendArgs::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(PutAppendArgs, _impl_._has_bits_),
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    PutAppendArgs_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::raftKVRpcProctoc::PutAppendArgs>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // bytes Key = 1;
    {::_pbi::TcParser::FastBS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(PutAppendArgs, _impl_.key_)}},
    // bytes Value = 2;
    {::_pbi::TcParser::FastBS1,
     {18, 1, 0,
      PROTOBUF_FIELD_OFFSET(PutAppendArgs, _impl_.value_)}},
    // bytes Op = 3;
    {::_pbi::TcParser::FastBS1,
     {26, 2, 0,
      PROTOBUF_FIELD_OFFSET(PutAppendArgs, _impl_.op_)}},
    // bytes ClientId = 4;
    {::_pbi::TcParser::FastBS1,
     {34, 3, 0,
      PROTOBUF_FIELD_OFFSET(PutAppendArgs, _impl_.clientid_)}},
    // int32 RequestId = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(PutAppendArgs, _impl_.requestid_), 4>(),
     {40, 4, 0,
      PROTOBUF_FIELD_OFFSET(PutAppendArgs, _impl_.requestid_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // bytes Key = 1;
    {PROTOBUF_FIELD_OFFSET(PutAppendArgs, _impl_.key_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // bytes Value = 2;
    {PROTOBUF_FIELD_OFFSET(PutAppendArgs, _impl_.value_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // bytes Op = 3;
    {PROTOBUF_FIELD_OFFSET(PutAppendArgs, _impl_.op_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // bytes ClientId = 4;
    {PROTOBUF_FIELD_OFFSET(PutAppendArgs, _impl_.clientid_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // int32 RequestId = 5;
    {PROTOBUF_FIELD_OFFSET(PutAppendArgs, _impl_.requestid_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void PutAppendArgs::Clear() {
// @@protoc_insertion_point(message_clear_start:raftKVRpcProctoc.PutAppendArgs)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.key_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.value_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _impl_.op_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      _impl_.clientid_.ClearNonDefaultToEmpty();
    }
  }
  _impl_.requestid_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL PutAppendArgs::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const PutAppendArgs& this_ = static_cast<const PutAppendArgs&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL PutAppendArgs::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const PutAppendArgs& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:raftKVRpcProctoc.PutAppendArgs)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // bytes Key = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_key().empty()) {
      const ::std::string& _s = this_._internal_key();
      target = stream->WriteBytesMaybeAliased(1, _s, target);
    }
  }

  // bytes Value = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_value().empty()) {
      const ::std::string& _s = this_._internal_value();
      target = stream->WriteBytesMaybeAliased(2, _s, target);
    }
  }

  // bytes Op = 3;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (!this_._internal_op().empty()) {
      const ::std::string& _s = this_._internal_op();
      target = stream->WriteBytesMaybeAliased(3, _s, target);
    }
  }

  // bytes ClientId = 4;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (!this_._internal_clientid().empty()) {
      const ::std::string& _s = this_._internal_clientid();
      target = stream->WriteBytesMaybeAliased(4, _s, target);
    }
  }

  // int32 RequestId = 5;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    if (this_._internal_requestid() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<5>(
              stream, this_._internal_requestid(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:raftKVRpcProctoc.PutAppendArgs)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t PutAppendArgs::ByteSizeLong(const MessageLite& base) {
  const PutAppendArgs& this_ = static_cast<const PutAppendArgs&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t PutAppendArgs::ByteSizeLong() const {
  const PutAppendArgs& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:raftKVRpcProctoc.PutAppendArgs)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    // bytes Key = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_key().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_key());
      }
    }
    // bytes Value = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!this_._internal_value().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_value());
      }
    }
    // bytes Op = 3;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (!this_._internal_op().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_op());
      }
    }
    // bytes ClientId = 4;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (!this_._internal_clientid().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_clientid());
      }
    }
    // int32 RequestId = 5;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (this_._internal_requestid() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_requestid());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void PutAppendArgs::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<PutAppendArgs*>(&to_msg);
  auto& from = static_cast<const PutAppendArgs&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:raftKVRpcProctoc.PutAppendArgs)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_key().empty()) {
        _this->_internal_set_key(from._internal_key());
      } else {
        if (_this->_impl_.key_.IsDefault()) {
          _this->_internal_set_key("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!from._internal_value().empty()) {
        _this->_internal_set_value(from._internal_value());
      } else {
        if (_this->_impl_.value_.IsDefault()) {
          _this->_internal_set_value("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (!from._internal_op().empty()) {
        _this->_internal_set_op(from._internal_op());
      } else {
        if (_this->_impl_.op_.IsDefault()) {
          _this->_internal_set_op("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (!from._internal_clientid().empty()) {
        _this->_internal_set_clientid(from._internal_clientid());
      } else {
        if (_this->_impl_.clientid_.IsDefault()) {
          _this->_internal_set_clientid("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (from._internal_requestid() != 0) {
        _this->_impl_.requestid_ = from._impl_.requestid_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void PutAppendArgs::CopyFrom(const PutAppendArgs& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:raftKVRpcProctoc.PutAppendArgs)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PutAppendArgs::InternalSwap(PutAppendArgs* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.key_, &other->_impl_.key_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.value_, &other->_impl_.value_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.op_, &other->_impl_.op_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.clientid_, &other->_impl_.clientid_, arena);
  swap(_impl_.requestid_, other->_impl_.requestid_);
}

::google::protobuf::Metadata PutAppendArgs::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class PutAppendReply::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<PutAppendReply>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(PutAppendReply, _impl_._has_bits_);
};

PutAppendReply::PutAppendReply(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PutAppendReply_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:raftKVRpcProctoc.PutAppendReply)
}
PROTOBUF_NDEBUG_INLINE PutAppendReply::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::raftKVRpcProctoc::PutAppendReply& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        err_(arena, from.err_) {}

PutAppendReply::PutAppendReply(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const PutAppendReply& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PutAppendReply_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  PutAppendReply* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:raftKVRpcProctoc.PutAppendReply)
}
PROTOBUF_NDEBUG_INLINE PutAppendReply::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        err_(arena) {}

inline void PutAppendReply::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
PutAppendReply::~PutAppendReply() {
  // @@protoc_insertion_point(destructor:raftKVRpcProctoc.PutAppendReply)
  SharedDtor(*this);
}
inline void PutAppendReply::SharedDtor(MessageLite& self) {
  PutAppendReply& this_ = static_cast<PutAppendReply&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.err_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL PutAppendReply::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) PutAppendReply(arena);
}
constexpr auto PutAppendReply::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(PutAppendReply),
                                            alignof(PutAppendReply));
}
constexpr auto PutAppendReply::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_PutAppendReply_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &PutAppendReply::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<PutAppendReply>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &PutAppendReply::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<PutAppendReply>(), &PutAppendReply::ByteSizeLong,
              &PutAppendReply::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(PutAppendReply, _impl_._cached_size_),
          false,
      },
      &PutAppendReply::kDescriptorMethods,
      &descriptor_table_kvServerRPC_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull PutAppendReply_class_data_ =
        PutAppendReply::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
PutAppendReply::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&PutAppendReply_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(PutAppendReply_class_data_.tc_table);
  return PutAppendReply_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2>
PutAppendReply::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(PutAppendReply, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    PutAppendReply_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::raftKVRpcProctoc::PutAppendReply>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bytes Err = 1;
    {::_pbi::TcParser::FastBS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(PutAppendReply, _impl_.err_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bytes Err = 1;
    {PROTOBUF_FIELD_OFFSET(PutAppendReply, _impl_.err_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void PutAppendReply::Clear() {
// @@protoc_insertion_point(message_clear_start:raftKVRpcProctoc.PutAppendReply)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _impl_.err_.ClearNonDefaultToEmpty();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL PutAppendReply::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const PutAppendReply& this_ = static_cast<const PutAppendReply&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL PutAppendReply::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const PutAppendReply& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:raftKVRpcProctoc.PutAppendReply)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // bytes Err = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_err().empty()) {
      const ::std::string& _s = this_._internal_err();
      target = stream->WriteBytesMaybeAliased(1, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:raftKVRpcProctoc.PutAppendReply)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t PutAppendReply::ByteSizeLong(const MessageLite& base) {
  const PutAppendReply& this_ = static_cast<const PutAppendReply&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t PutAppendReply::ByteSizeLong() const {
  const PutAppendReply& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:raftKVRpcProctoc.PutAppendReply)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // bytes Err = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_err().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_err());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void PutAppendReply::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<PutAppendReply*>(&to_msg);
  auto& from = static_cast<const PutAppendReply&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:raftKVRpcProctoc.PutAppendReply)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!from._internal_err().empty()) {
      _this->_internal_set_err(from._internal_err());
    } else {
      if (_this->_impl_.err_.IsDefault()) {
        _this->_internal_set_err("");
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void PutAppendReply::CopyFrom(const PutAppendReply& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:raftKVRpcProctoc.PutAppendReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PutAppendReply::InternalSwap(PutAppendReply* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.err_, &other->_impl_.err_, arena);
}

::google::protobuf::Metadata PutAppendReply::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace raftKVRpcProctoc
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_kvServerRPC_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
